# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.DurationField(),
        ),
        migrations.AlterUniqueTogether(
            name='thing',
            unique_together=set([('user', 'name')]),
        ),
    ]
