# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20160310_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='when',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='next_job_at',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('thing', 'name')]),
        ),
    ]
